"""CLI entrypoint for chatcrs."""

from __future__ import annotations

import json
from pathlib import Path

import click

import chatcrs.debug as debug_management
import chatcrs.local as local_management
import chatcrs.remote as remote_management
from chatcrs import __version__
from chatcrs.cutover import formal_single_active_precheck
from chatcrs.inspect import inspect_crs_layout
from chatcrs.nginx import plan_nginx_cutover
from chatcrs.paths import CrsPaths
from chatcrs.verify import verify_sidecar


def _echo_json(payload: dict) -> None:
    click.echo(json.dumps(payload, ensure_ascii=False, indent=2))


def _paths(**overrides: object) -> CrsPaths:
    values = {key: value for key, value in overrides.items() if value is not None}
    return CrsPaths(**values)


@click.group(context_settings={"help_option_names": ["-h", "--help"]})
@click.version_option(__version__, prog_name="chatcrs")
def main() -> None:
    """CRS management helpers for ChatArch."""


@main.command(name="health")
@click.option("--base-url", default=None, help="CRS base URL. Defaults to CHATCRS_BASE_URL or local CRS default.")
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def health_command(base_url: str | None, json_output: bool) -> None:
    """Verify the CRS /health endpoint."""

    payload = local_management.health_check(base_url)
    if json_output:
        _echo_json(payload)
    else:
        click.echo(f"ok={payload['ok']} base_url={payload['base_url']} status={payload['health']['status']}")


@main.group(name="local")
def local_group() -> None:
    """Manage a local CRS installed by ChatUp."""


@local_group.command(name="verify")
@click.option("--base-url", default=None, help="CRS base URL. Defaults to CHATCRS_BASE_URL or local CRS default.")
@click.option(
    "--secrets-file",
    type=click.Path(path_type=Path, exists=True, dir_okay=False),
    default=None,
    help="Local secrets file generated by ChatUp; enables admin login smoke.",
)
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def local_verify_command(base_url: str | None, secrets_file: Path | None, json_output: bool) -> None:
    """Verify local CRS health, web, API route, and optional admin login."""

    payload = local_management.verify_local_crs(base_url=base_url, secrets_file=secrets_file)
    if json_output:
        _echo_json(payload)
    else:
        click.echo(f"ok={payload['ok']} base_url={payload['base_url']} mutated={payload['mutated']}")


@main.group(name="debug")
def debug_group() -> None:
    """Manage only the isolated CRS debug service on port 12392."""


@debug_group.command(name="status")
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def debug_status_command(json_output: bool) -> None:
    """Inspect debug health, tmux, Redis, Git, and safe settings."""

    payload = debug_management.debug_status()
    if json_output:
        _echo_json(payload)
    else:
        click.echo(
            f"ok={payload['ok']} health={payload['health']['status']} "
            f"tmux={payload['tmux']['active']} redis={payload['redis']['ping']} "
            f"mutated={payload['mutated']}"
        )


@debug_group.command(name="logs")
@click.option("--lines", type=click.IntRange(1, 2000), default=100, show_default=True)
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def debug_logs_command(lines: int, json_output: bool) -> None:
    """Read redacted tail lines from the debug service log."""

    try:
        payload = debug_management.debug_logs(lines)
    except (OSError, ValueError) as exc:
        raise click.ClickException(str(exc)) from exc
    if json_output:
        _echo_json(payload)
    else:
        click.echo("\n".join(payload.get("lines", [])))


@debug_group.command(name="restart")
@click.option(
    "--execute",
    is_flag=True,
    default=False,
    help="Restart only tmux session crs-debug-12392. Without this flag, print a plan.",
)
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
@click.pass_context
def debug_restart_command(ctx: click.Context, execute: bool, json_output: bool) -> None:
    """Plan or execute a guarded debug-only restart."""

    try:
        payload = debug_management.restart_debug(execute=execute)
    except (OSError, RuntimeError, ValueError) as exc:
        raise click.ClickException(str(exc)) from exc
    if json_output:
        _echo_json(payload)
    else:
        click.echo(
            f"ok={payload['ok']} mode={payload['mode']} "
            f"mutated={payload['mutated']} target={payload['target']}"
        )
    if execute and not payload["ok"]:
        ctx.exit(1)


@debug_group.group(name="settings")
def debug_settings_group() -> None:
    """Show or update a whitelist of non-secret debug settings."""


@debug_settings_group.command(name="show")
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def debug_settings_show_command(json_output: bool) -> None:
    """Show non-secret debug settings and protected isolation keys."""

    payload = debug_management.show_debug_settings()
    if json_output:
        _echo_json(payload)
    else:
        for key, value in payload["settings"].items():
            click.echo(f"{key}={value}")


@debug_settings_group.command(name="set")
@click.argument("key")
@click.argument("value")
@click.option(
    "--execute",
    is_flag=True,
    default=False,
    help="Write the debug .env and restart only debug. Without this flag, print a plan.",
)
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def debug_settings_set_command(key: str, value: str, execute: bool, json_output: bool) -> None:
    """Plan or apply one whitelisted setting to debug only."""

    try:
        payload = debug_management.set_debug_setting(key.upper(), value, execute=execute)
    except (OSError, RuntimeError, ValueError) as exc:
        raise click.ClickException(str(exc)) from exc
    if json_output:
        _echo_json(payload)
    else:
        click.echo(
            f"ok={payload['ok']} mode={payload['mode']} changed={payload['changed']} "
            f"mutated={payload['mutated']} setting={payload['setting']}"
        )


@debug_group.group(name="upgrade")
def debug_upgrade_group() -> None:
    """Plan or apply an exact ChatArch dev upgrade to debug only."""


@debug_upgrade_group.command(name="plan")
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def debug_upgrade_plan_command(json_output: bool) -> None:
    """Compare the debug checkout with remote ChatArch dev without mutation."""

    payload = debug_management.upgrade_plan()
    if json_output:
        _echo_json(payload)
    else:
        click.echo(
            f"ok={payload['ok']} current={payload['current']['sha']} "
            f"remote_dev={payload['dev']['remote_sha']} "
            f"already_target_tree={payload['already_target_tree']} mutated={payload['mutated']}"
        )


@debug_upgrade_group.command(name="apply")
@click.option("--expected-sha", default=None, help="Reviewed 40-character remote dev SHA.")
@click.option(
    "--execute",
    is_flag=True,
    default=False,
    help="Apply the exact upgrade to debug. Without this flag, return the upgrade plan.",
)
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def debug_upgrade_apply_command(expected_sha: str | None, execute: bool, json_output: bool) -> None:
    """Plan or execute a guarded debug-only upgrade."""

    try:
        payload = debug_management.apply_debug_upgrade(expected_sha, execute=execute)
    except (OSError, RuntimeError, ValueError) as exc:
        raise click.ClickException(str(exc)) from exc
    if json_output:
        _echo_json(payload)
    else:
        click.echo(
            f"ok={payload['ok']} mode={payload['mode']} "
            f"mutated={payload['mutated']} already_target_tree={payload['already_target_tree']}"
        )


@main.command(name="inspect")
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def inspect_command(json_output: bool) -> None:
    """Inspect known CRS services without mutating them."""

    payload = inspect_crs_layout()
    if json_output:
        _echo_json(payload)
    else:
        click.echo(f"old={payload['old']['health'].get('status')} new={payload['new']['health'].get('status')} mutated={payload['mutated']}")


@main.group(name="verify")
def verify_group() -> None:
    """Run read-only verification checks."""


@verify_group.command(name="sidecar")
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def verify_sidecar_command(json_output: bool) -> None:
    """Verify old/new sidecar CRS services."""

    payload = verify_sidecar()
    if json_output:
        _echo_json(payload)
    else:
        click.echo(f"ok={payload['ok']} mutated={payload['mutated']}")


@verify_group.command(name="images")
@click.option("--base-url", default=None, help="CRS root URL. Defaults to CHATCRS_BASE_URL or local CRS.")
@click.option(
    "--openai-env-file",
    type=click.Path(path_type=Path, exists=True, dir_okay=False),
    default=None,
    help="Env file containing OPENAI_API_KEY. Defaults to CHATCRS_OPENAI_ENV_FILE or the active ChatEnv OpenAI profile.",
)
@click.option("--regular-model", default="gpt-5.5", show_default=True)
@click.option("--image-model", default="gpt-image-2", show_default=True)
@click.option(
    "--prompt",
    default="A single orange triangle on a pale blue grid, minimalist icon, no text.",
    show_default=True,
)
@click.option(
    "--output",
    "output_path",
    type=click.Path(path_type=Path, dir_okay=False),
    default=Path("chatcrs-image-acceptance.png"),
    show_default=True,
)
@click.option(
    "--execute-image",
    is_flag=True,
    default=False,
    help="Perform the billable Images request and write the PNG. Without this flag only key and regular-model gates run.",
)
@click.option("--timeout", "timeout_seconds", type=float, default=600.0, show_default=True)
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def verify_images_command(
    base_url: str | None,
    openai_env_file: Path | None,
    regular_model: str,
    image_model: str,
    prompt: str,
    output_path: Path,
    execute_image: bool,
    timeout_seconds: float,
    json_output: bool,
) -> None:
    """Verify CRS API-key routing, optionally including real image generation."""

    try:
        payload = local_management.verify_images_api(
            base_url=base_url,
            openai_env_file=openai_env_file,
            regular_model=regular_model,
            image_model=image_model,
            prompt=prompt,
            output_path=output_path,
            execute_image=execute_image,
            timeout_seconds=timeout_seconds,
        )
    except (OSError, ValueError) as exc:
        raise click.ClickException(str(exc)) from exc
    if json_output:
        _echo_json(payload)
    else:
        click.echo(
            f"ok={payload['ok']} key={payload['key_info']['ok']} "
            f"regular={payload['regular_model']['ok']} image={payload['image']['ok']} "
            f"executed={payload['image']['executed']} mutated={payload['mutated']}"
        )


def _remote_client(
    *,
    profile: str,
    base_url: str | None,
    api_key: str | None,
    username: str | None,
    password: str | None,
    admin_token: str | None,
    timeout: float,
) -> remote_management.CrsHttpClient:
    return remote_management.client_from_options(
        profile=profile,
        base_url=base_url,
        api_key=api_key,
        username=username,
        password=password,
        admin_token=admin_token,
        timeout=timeout,
    )


def _common_remote_options(function):
    function = click.option("--timeout", type=float, default=20.0, show_default=True)(function)
    function = click.option("--admin-token", default=None, help="Admin bearer token. Prefer ChatEnv profile for real use.")(function)
    function = click.option("--password", default=None, help="Admin password. Prefer ChatEnv profile for real use.")(function)
    function = click.option("--username", default=None, help="Admin username. Prefer ChatEnv profile for real use.")(function)
    function = click.option("--api-key", default=None, help="CRS API key for non-admin endpoints. Prefer ChatEnv profile.")(function)
    function = click.option("--base-url", default=None, help="Remote CRS base URL. Defaults to CRS_API_BASE in ChatEnv profile.")(function)
    function = click.option("--profile", default="admin", show_default=True, help="CRS ChatEnv profile under envs/CRS/<profile>.env.")(function)
    return function


@main.group(name="admin")
def admin_group() -> None:
    """Remote CRS administrator operations via HTTPS Admin API."""


@admin_group.command(name="login")
@_common_remote_options
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def admin_login_command(
    profile: str,
    base_url: str | None,
    api_key: str | None,
    username: str | None,
    password: str | None,
    admin_token: str | None,
    timeout: float,
    json_output: bool,
) -> None:
    """Verify CRS admin login without printing the session token."""

    try:
        client = _remote_client(
            profile=profile,
            base_url=base_url,
            api_key=api_key,
            username=username,
            password=password,
            admin_token=admin_token,
            timeout=timeout,
        )
        payload = client.login()
    except (OSError, ValueError, remote_management.CrsApiError) as exc:
        raise click.ClickException(str(exc)) from exc
    if json_output:
        _echo_json(payload)
    else:
        click.echo(f"ok={payload['ok']} status={payload['status']} token_present={payload['token_present']}")


@admin_group.group(name="accounts")
def admin_accounts_group() -> None:
    """Inspect or refresh remote CRS account state."""


@admin_accounts_group.command(name="usage")
@_common_remote_options
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def admin_accounts_usage_command(
    profile: str,
    base_url: str | None,
    api_key: str | None,
    username: str | None,
    password: str | None,
    admin_token: str | None,
    timeout: float,
    json_output: bool,
) -> None:
    """List OpenAI/Codex account usage and scheduling metadata."""

    try:
        payload = _remote_client(
            profile=profile,
            base_url=base_url,
            api_key=api_key,
            username=username,
            password=password,
            admin_token=admin_token,
            timeout=timeout,
        ).accounts_usage()
    except (OSError, ValueError, remote_management.CrsApiError) as exc:
        raise click.ClickException(str(exc)) from exc
    if json_output:
        _echo_json(payload)
    else:
        click.echo(f"ok={payload['ok']} accounts={payload['count']} mutated={payload['mutated']}")


@admin_accounts_group.command(name="refresh-status")
@_common_remote_options
@click.argument("account_id")
@click.option("--execute", is_flag=True, default=False, help="Actually call CRS reset-status. Without it, print a dry-run plan.")
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def admin_accounts_refresh_status_command(
    profile: str,
    base_url: str | None,
    api_key: str | None,
    username: str | None,
    password: str | None,
    admin_token: str | None,
    timeout: float,
    account_id: str,
    execute: bool,
    json_output: bool,
) -> None:
    """Reset a CRS OpenAI account status after transient failures."""

    if not execute:
        payload = {
            "ok": True,
            "mutated": False,
            "would_call": f"POST /admin/openai-accounts/{account_id}/reset-status",
            "account_id": account_id,
        }
    else:
        try:
            payload = _remote_client(
                profile=profile,
                base_url=base_url,
                api_key=api_key,
                username=username,
                password=password,
                admin_token=admin_token,
                timeout=timeout,
            ).reset_openai_account_status(account_id)
        except (OSError, ValueError, remote_management.CrsApiError) as exc:
            raise click.ClickException(str(exc)) from exc
    if json_output:
        _echo_json(payload)
    else:
        click.echo(f"ok={payload['ok']} account_id={account_id} mutated={payload['mutated']}")


@admin_group.group(name="keys")
def admin_keys_group() -> None:
    """Inspect remote CRS API keys with admin privileges."""


@admin_keys_group.command(name="list")
@_common_remote_options
@click.option("--include-stats", is_flag=True, default=False, help="Fetch batch usage and last-account attribution for each key.")
@click.option("--time-range", default="all", show_default=True, type=click.Choice(["today", "7days", "30days", "all"]))
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def admin_keys_list_command(
    profile: str,
    base_url: str | None,
    api_key: str | None,
    username: str | None,
    password: str | None,
    admin_token: str | None,
    timeout: float,
    include_stats: bool,
    time_range: str,
    json_output: bool,
) -> None:
    """List CRS API key metadata, optionally including usage stats."""

    try:
        payload = _remote_client(
            profile=profile,
            base_url=base_url,
            api_key=api_key,
            username=username,
            password=password,
            admin_token=admin_token,
            timeout=timeout,
        ).api_keys(include_stats=include_stats, time_range=time_range)
    except (OSError, ValueError, remote_management.CrsApiError) as exc:
        raise click.ClickException(str(exc)) from exc
    if json_output:
        _echo_json(payload)
    else:
        click.echo(f"ok={payload['ok']} keys={payload['count']} mutated={payload['mutated']}")


@admin_keys_group.command(name="show")
@_common_remote_options
@click.argument("key_id")
@click.option("--include-stats/--no-include-stats", default=True, show_default=True)
@click.option("--time-range", default="all", show_default=True, type=click.Choice(["today", "7days", "30days", "all"]))
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def admin_keys_show_command(
    profile: str,
    base_url: str | None,
    api_key: str | None,
    username: str | None,
    password: str | None,
    admin_token: str | None,
    timeout: float,
    key_id: str,
    include_stats: bool,
    time_range: str,
    json_output: bool,
) -> None:
    """Show one CRS API key by id or name."""

    try:
        payload = _remote_client(
            profile=profile,
            base_url=base_url,
            api_key=api_key,
            username=username,
            password=password,
            admin_token=admin_token,
            timeout=timeout,
        ).api_key_detail(key_id, include_stats=include_stats, time_range=time_range)
    except (OSError, ValueError, remote_management.CrsApiError) as exc:
        raise click.ClickException(str(exc)) from exc
    if json_output:
        _echo_json(payload)
    else:
        click.echo(f"ok={payload['ok']} query={key_id} mutated={payload['mutated']}")


@main.group(name="key")
def key_group() -> None:
    """CRS API-key-only operations that do not require admin login."""


@key_group.command(name="info")
@_common_remote_options
@click.option("--path", "info_path", default="/openai/key-info", show_default=True, help="CRS key-info endpoint path.")
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def key_info_command(
    profile: str,
    base_url: str | None,
    api_key: str | None,
    username: str | None,
    password: str | None,
    admin_token: str | None,
    timeout: float,
    info_path: str,
    json_output: bool,
) -> None:
    """Query CRS key-info using only a CRS API key."""

    try:
        payload = _remote_client(
            profile=profile,
            base_url=base_url,
            api_key=api_key,
            username=username,
            password=password,
            admin_token=admin_token,
            timeout=timeout,
        ).key_info(path=info_path)
    except (OSError, ValueError, remote_management.CrsApiError) as exc:
        raise click.ClickException(str(exc)) from exc
    if json_output:
        _echo_json(payload)
    else:
        click.echo(f"ok={payload['ok']} status={payload['status']} mutated={payload['mutated']}")


@main.group(name="nginx")
def nginx_group() -> None:
    """Plan Nginx CRS routing changes."""


@nginx_group.command(name="plan-cutover")
@click.option("--config", "config_path", default="/etc/nginx/sites-available/single/crs.conf", show_default=True)
@click.option("--from-port", default=12390, show_default=True, type=int)
@click.option("--to-port", default=12391, show_default=True, type=int)
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def nginx_plan_cutover_command(config_path: str, from_port: int, to_port: int, json_output: bool) -> None:
    """Generate a read-only Nginx cutover diff."""

    payload = plan_nginx_cutover(config_path, from_port=from_port, to_port=to_port)
    if json_output:
        _echo_json(payload)
    else:
        click.echo(payload.get("diff", ""))


@main.group(name="cutover")
def cutover_group() -> None:
    """Formal single-active cutover checks."""


@cutover_group.command(name="precheck")
@click.option("--json-output", is_flag=True, default=False, help="Render structured JSON output.")
def cutover_precheck_command(json_output: bool) -> None:
    """Check readiness for a formal single-active DB0 cutover."""

    payload = formal_single_active_precheck()
    if json_output:
        _echo_json(payload)
    else:
        click.echo(f"ready={payload['ready_for_formal_cutover_after_packages']} mutated={payload['mutated']}")


if __name__ == "__main__":
    main()
