"Typed environment configuration for ChatCRS."

from chatenv import BaseEnvConfig, EnvField


class ChatcrsConfig(BaseEnvConfig):
    "ChatCRS ChatEnv configuration."

    _title = "ChatCRS Configuration"
    _aliases = ["chatcrs"]
    _storage_dir = "Chatcrs"

    @classmethod
    def test(cls) -> None:
        """Validate schema registration without external side effects."""

        print(f"Testing {cls._title}...")
        print("Schema loaded; no network test is required.")

    CHATCRS_BASE_URL = EnvField(
        "CHATCRS_BASE_URL",
        desc="CRS base URL, for example http://127.0.0.1:12392",
    )

    CHATCRS_SECRETS_FILE = EnvField(
        "CHATCRS_SECRETS_FILE",
        desc="Path to a local CRS secrets file generated by ChatUp",
        is_sensitive=True,
    )

    CHATCRS_API_KEY = EnvField(
        "CHATCRS_API_KEY",
        desc="CRS API key",
        is_sensitive=True,
    )


__all__ = ["ChatcrsConfig"]
